# Generated by Django 5.2.8 on 2025-11-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FichaMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=90, verbose_name='Nombre del dueño')),
                ('mascota', models.CharField(max_length=30, verbose_name='Nombre de la mascota')),
                ('especie', models.CharField(max_length=40, verbose_name='Especie de la mascota')),
                ('edad', models.IntegerField(verbose_name='Edad de la mascota')),
                ('peso', models.IntegerField(verbose_name='Peso de la mascota')),
                ('vacunas', models.TextField(max_length=60, verbose_name='Descripción de vacunas')),
                ('tratamientos_apli', models.TextField(max_length=200, verbose_name='Tratamientos aplicados')),
                ('tratamientos_sig', models.TextField(max_length=100, verbose_name='Siguiente tratamiento por aplicar')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono de contacto')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última vez actualizado')),
            ],
        ),
    ]
