# Generated by Django 4.2.24 on 2025-11-21 16:26

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de Veterinario')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cuenta de usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunes', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), size=16)),
                ('martes', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), size=16)),
                ('miercoles', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), size=16)),
                ('jueves', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), size=16)),
                ('viernes', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), size=16)),
                ('sabado', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), size=16)),
                ('domingo', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), size=16)),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última vez actualizado')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinarios.veterinario', verbose_name='Veterinario')),
            ],
        ),
    ]
