# Generated by Django 5.2.8 on 2025-11-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinario',
            name='nombre',
            field=models.CharField(max_length=120, verbose_name='Nombre de Veterinario'),
        ),
    ]
