# Generated by Django 4.2.24 on 2025-11-28 00:38

from django.db import migrations
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarios', '0002_alter_veterinario_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='domingo',
            field=django_jsonform.models.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='horario',
            name='jueves',
            field=django_jsonform.models.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='horario',
            name='lunes',
            field=django_jsonform.models.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='horario',
            name='martes',
            field=django_jsonform.models.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='horario',
            name='miercoles',
            field=django_jsonform.models.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='horario',
            name='sabado',
            field=django_jsonform.models.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='horario',
            name='viernes',
            field=django_jsonform.models.fields.JSONField(),
        ),
    ]
