# Generated by Django 4.2.24 on 2025-11-28 00:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarios', '0003_alter_horario_domingo_alter_horario_jueves_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='soy_yo',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), blank=True, null=True, size=16),
        ),
    ]
