# Generated by Django 4.2.24 on 2025-11-28 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarios', '0004_horario_soy_yo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='soy_yo',
        ),
    ]
