# Generated by Django 4.2.24 on 2025-11-28 00:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarios', '0005_remove_horario_soy_yo'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de registro'),
            preserve_default=False,
        ),
    ]
