# Generated by Django 4.2.24 on 2025-11-28 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarios', '0006_horario_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='created',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='updated',
        ),
    ]
