# Generated by Django 4.2.24 on 2025-11-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarios', '0007_remove_horario_created_remove_horario_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Última vez actualizado'),
        ),
    ]
