# Generated by Django 4.2.24 on 2025-11-28 01:00

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarios', '0009_horario_tickeame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='tickeame',
            field=django_jsonform.models.fields.ArrayField(base_field=models.BooleanField(default=False), blank=True, null=True, size=None),
        ),
    ]
