# Generated by Django 4.2.24 on 2025-11-28 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarios', '0010_alter_horario_tickeame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='tickeame',
        ),
    ]
