# Generated by Django 4.2.24 on 2025-12-05 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('veterinarios', '0011_remove_horario_tickeame'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recepcionista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre de Recepcionista')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cuenta de usuario')),
            ],
        ),
    ]
