# Generated by Django 5.2.8 on 2025-11-21 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fichas_mascota', '0001_initial'),
        ('veterinarios', '0002_alter_veterinario_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha agendada')),
                ('hora_inicial', models.IntegerField(max_length=2, verbose_name='Bloque inicial de cita')),
                ('hora_final', models.IntegerField(max_length=2, verbose_name='Bloque final de cita')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], verbose_name='Estado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última vez actualizado')),
                ('ficha_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichas_mascota.fichamascota', verbose_name='Ficha Cliente')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinarios.veterinario', verbose_name='Veterinario asignado')),
            ],
        ),
    ]
