# Generated by Django 5.2.8 on 2025-11-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='hora_final',
            field=models.IntegerField(verbose_name='Bloque final de cita'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='hora_inicial',
            field=models.IntegerField(verbose_name='Bloque inicial de cita'),
        ),
    ]
