# Generated by Django 4.2.24 on 2025-11-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0002_alter_cita_hora_final_alter_cita_hora_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], max_length=9, verbose_name='Estado'),
        ),
    ]
