# Generated by Django 4.2.24 on 2025-12-05 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarios', '0012_recepcionista'),
        ('horarios', '0003_alter_cita_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chequeado', models.BooleanField(default=False, verbose_name='Chequeado')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Fecha de creación')),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.cita', verbose_name='Cita cancelada')),
                ('recepcionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinarios.recepcionista', verbose_name='Recepcionista')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
            },
        ),
    ]
