# Generated by Django 4.2.24 on 2025-12-05 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0004_notificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='hora_final',
        ),
    ]
